spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true      # SQL 쿼리 출력
  #  defer-datasource-initialization: true # 초기 데이터 삽입을 위해 필요하다.
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG